add-payment-stats-service
haribo27/payment-stats pull request #6
Opened 2024-11-11 05:58 UTC by haribo27

Сделал сервис по получению статистики платежей/переводов

2024-11-12 13:47 UTC, PavelAndryushenko requested changes
Все сделано очень хорошо, инструменты применены правильно, но замечания нужно поправить

2024-11-12 13:47 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/dto/PaymentStatsDto.java
> +    @QueryProjection
Это зависимость из JPA - ее не должно быть в слое ДТО, где описываются сущности из запросов

2024-11-12 13:47 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/exception/ErrorResponse.java
> +@Data
Тут можно Data заменить на Getter + EqualsAndHashCode, если нам нужно объекты сравнивать - а сеттеры и конструктор без аргументов тут не нужны, поскольку объект у нас иммутабельный

2024-11-12 13:47 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/model/Payment.java
> +    private boolean intraBankTransfer;
Тут еще остался примитив в сущности

2024-11-12 13:47 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/service/PaymentStatsService.java
> +    TransferStatsDto getTransfersStats(@Valid ClientRequestStatsDto request);
Тут у нас валидация на уровне сервисного бина - если request нам приходит из контроллера, то валидацию лучше делать там

2024-11-12 13:47 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/service/PaymentStatsServiceImpl.java
> +                .fetch();
Вот эта вся логика получения данных из БД - ее логичнее вынести в репозиторий, поскольку вся логика по работе непосредственно с хранилищем должна быть там

2024-11-12 13:47 UTC, PavelAndryushenko commented on stats/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=none
Тут лучше поставить valid - пусть Hibernate проверяет сущности на соответствие таблицам в БД

2024-11-12 13:47 UTC, PavelAndryushenko commented on updater/src/main/java/ru/zubcov/paymentstats/updater/messaging/payment/PaymentDto.java
>  @Data
PaymentDTO корректно десериализуется из json? Просто, насколько я помню, ему на конструктор нужно повесить JsonCreator, чтобы он использовал конструктор для инициализации класса, а иначе он будет Setter использовать по умолчанию, но если все работает, то можно так оставить

2024-11-12 13:47 UTC, PavelAndryushenko commented on updater/src/main/java/ru/zubcov/paymentstats/updater/okvedApiClient/dto/SuggestionResponseDto.java
>      @Data
Если класс у нас иммутабельный, то Data нужно заменять на Value или Getter - иначе Ломбок сгенерит сеттеры и конструктор без параметров, а они тут не нужны

2024-11-12 13:47 UTC, PavelAndryushenko commented on updater/src/main/resources/db/migration/V1__init_payment_table.sql
> +    receive_client_bank_bik VARCHAR(20) NOT NULL,
Это скрипты миграции - их не желательно редактировать. Лучше все изменения делать новым ченджсетом - у нас тут все гладко будет проходить, поскольку каждый раз схема в БД создается заново, но если работать с существующей схемой данных, например, на стендах, то будут ошибки валидации чейнджсетов

2024-11-13 08:48 UTC, haribo27 commented on stats/src/main/java/ru/zubcov/paymentstats/stats/service/PaymentStatsService.java
> +    TransferStatsDto getTransfersStats(@Valid ClientRequestStatsDto request);
случайно она здесь появилась

2024-11-13 08:59 UTC, haribo27 commented on updater/src/main/java/ru/zubcov/paymentstats/updater/messaging/payment/PaymentDto.java
>  @Data
все работает. Отправляю запросы с другого приложения через rest и kafka producer

2024-11-13 09:03 UTC, haribo27 commented on updater/src/main/java/ru/zubcov/paymentstats/updater/okvedApiClient/dto/SuggestionResponseDto.java
>      @Data
спасибо, не знал про аннотацию @Value, удобно

2024-11-13 09:03 UTC, haribo27 commented on updater/src/main/resources/db/migration/V1__init_payment_table.sql
> +    receive_client_bank_bik VARCHAR(20) NOT NULL,
хорошо, буду иметь в виду

2024-11-15 09:30 UTC, PavelAndryushenko approved these changes
Можно мерджить, замечания можно поправить в следующих задачах

2024-11-15 09:30 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/model/PaymentStatsDto.java
> +@Data
Тут осталась Data в ДТО - нужно либо заменить ее на Getter, либо, если нужны сеттеры, нужно атрибуты делать не финальными, но это ДТО, она иммутабельной должна быть

2024-11-15 09:30 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/model/TransferStatsDto.java
> +@Data
Те же комментарии, что и в PaymentStatsDto

2024-11-15 09:30 UTC, PavelAndryushenko commented on stats/src/main/java/ru/zubcov/paymentstats/stats/repository/CustomPaymentRepository.java
> +    List<PaymentStatsDto> getClientPaymentStats(ClientRequestStatsDto requestStatsDto);
Тут наоборот - у тебя сущности из клиентского слоя тянутся в слой репозиториев - это не очень хорошо, желательно их изолировать и тянуть, максимум, в слой сервисов

2024-11-21 06:57 UTC, merged